# Generated by Django 4.2.7 on 2023-11-20 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('participated_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(null=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chats.chat')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='members.member')),
            ],
        ),
    ]
