# Generated by Django 4.2.7 on 2023-12-23 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='headcount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
