# Generated by Django 4.2.7 on 2023-12-24 06:34

from django.db import migrations


class Migration(migrations.Migration):
    table_name = "chats"
    index_name = "name_fulltext_index"
    field_name = "name"

    dependencies = [
        ('chats', '0003_alter_chat_name'),
    ]
    operations = [
        migrations.RunSQL(
            (f'CREATE FULLTEXT INDEX {index_name} ON {table_name}({field_name}) WITH PARSER ngram',),
            (f'DROP INDEX {index_name} on {table_name}',),
        ),
    ]
