# Generated by Django 4.2.7 on 2023-12-27 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0005_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='chats.chat'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bookmarks', to=settings.AUTH_USER_MODEL),
        ),
    ]
