# Generated by Django 4.2.7 on 2023-12-30 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0006_alter_bookmark_chat_alter_bookmark_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='bookmark',
            index=models.Index(fields=['member', 'chat'], name='bookmarks_member__7674fa_idx'),
        ),
    ]
